"""text_proxy_id

Revision ID: 73d12093abf9
Revises: 758e073f6f42
Create Date: 2023-12-02 12:19:49.728122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73d12093abf9'
down_revision: Union[str, None] = '758e073f6f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("text") as alter_table_text_op:
        alter_table_text_op.add_column(
            sa.Column("proxy_id", sa.Integer(), server_default=sa.literal(0))
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text', 'proxy_id')
    # ### end Alembic commands ###
