"""topic_return_kor_eng

Revision ID: 758e073f6f42
Revises: c7f913827b11
Create Date: 2023-11-24 15:30:49.380695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '758e073f6f42'
down_revision: Union[str, None] = 'c7f913827b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table("topic")
    topic = op.create_table(
        "topic",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tag", sa.String(), nullable=False),
        sa.Column("topic_kor", sa.String(), nullable=False),
        sa.Column("topic_eng", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    topic_data = [{'tag': 'C',
                   'topic_kor': '좋아하는 책에 대한 이야기',
                   'topic_eng': 'Talking about favorite books'},
                  {'tag': 'C',
                   'topic_kor': '좋아하는 책 장르에 대한 이야기',
                   'topic_eng': 'Discussing favorite book genres'},
                  {'tag': 'C',
                   'topic_kor': '좋아하는 작가에 대한 이야기',
                   'topic_eng': 'Talking about favorite authors'},
                  {'tag': 'C',
                   'topic_kor': '최근에 본 영화에 대한 이야기',
                   'topic_eng': 'Discussing recent movies watched'},
                  {'tag': 'C',
                   'topic_kor': '자주 보는 TV 프로그램에 대한 이야기',
                   'topic_eng': 'Talking about favorite TV programs'},
                  {'tag': 'C',
                   'topic_kor': '재미있는 넷플릭스 컨텐츠에 대한 이야기',
                   'topic_eng': 'Discussing interesting Netflix content'},
                  {'tag': 'C',
                   'topic_kor': '마블 영화에 대한 이야기',
                   'topic_eng': 'Talking about Marvel movies'},
                  {'tag': 'C',
                   'topic_kor': '좋아하는 영화 장르에 대한 이야기',
                   'topic_eng': 'Discussing favorite movie genres'},
                  {'tag': 'C',
                   'topic_kor': '인생 영화나 드라마에 대한 이야기',
                   'topic_eng': 'Talking about life-changing movies or dramas'},
                  {'tag': 'C',
                   'topic_kor': '최악의 영화나 드라마에 대한 이야기',
                   'topic_eng': 'Discussing worst movies or dramas'},
                  {'tag': 'C',
                   'topic_kor': '좋아하는 배우에 대한 이야기',
                   'topic_eng': 'Talking about favorite actors'},
                  {'tag': 'C',
                   'topic_kor': '좋아하는 영화 감독에 대한 이야기',
                   'topic_eng': 'Talking about favorite movie directors'},
                  {'tag': 'C', 'topic_kor': 'K-POP에 대한 이야기', 'topic_eng': 'Discussing K-POP'},
                  {'tag': 'C',
                   'topic_kor': '좋아하는 음악 장르에 대한 이야기',
                   'topic_eng': 'Talking about favorite music genres'},
                  {'tag': 'C',
                   'topic_kor': '좋아하는 가수에 대한 이야기',
                   'topic_eng': 'Talking about favorite singers'},
                  {'tag': 'C',
                   'topic_kor': '좋아하는 노래에 대한 이야기',
                   'topic_eng': 'Talking about favorite songs'},
                  {'tag': 'C',
                   'topic_kor': '가장 기억에 남는 여행지에 대한 이야기',
                   'topic_eng': 'Discussing most memorable travel destinations'},
                  {'tag': 'C',
                   'topic_kor': '최악의 여행지에 대한 이야기',
                   'topic_eng': 'Discussing worst travel destinations'},
                  {'tag': 'C',
                   'topic_kor': '여행 중 겪었던 재밌는 에피소드에 대한 이야기',
                   'topic_eng': 'Talking about amusing travel experiences'},
                  {'tag': 'C',
                   'topic_kor': '여행 중 먹었던 음식에 대한 이야기',
                   'topic_eng': 'Talking about foods eaten during travels'},
                  {'tag': 'C',
                   'topic_kor': '자신의 MBTI에 대한 이야기',
                   'topic_eng': 'Talking about MBTI personality types'},
                  {'tag': 'C',
                   'topic_kor': '좋아하는 스포츠에 대한 이야기',
                   'topic_eng': 'Talking about favorite sports'},
                  {'tag': 'C',
                   'topic_kor': '좋아하는 스포츠 스타에 대한 이야기',
                   'topic_eng': 'Talking about favorite sports stars'},
                  {'tag': 'C',
                   'topic_kor': '휴일에는 어떤 일을 하는지에 대한 이야기',
                   'topic_eng': 'Discussing activities on holidays'},
                  {'tag': 'C',
                   'topic_kor': '본인의 취미에 대한 이야기',
                   'topic_eng': 'Discussing personal hobbies'},
                  {'tag': 'C',
                   'topic_kor': '좋아하는 음식이나 맛집에 대한 이야기',
                   'topic_eng': 'Talking about favorite foods or restaurants'},
                  {'tag': 'C',
                   'topic_kor': '카페에서 어떤 커피를 주로 마시는지에 대한 이야기',
                   'topic_eng': 'Discussing preferred coffee at cafes'},
                  {'tag': 'C',
                   'topic_kor': '좋아하는 뮤지컬이나 연극에 대한 이야기',
                   'topic_eng': 'Talking about favorite musicals or plays'},
                  {'tag': 'C',
                   'topic_kor': '가장 좋아하는 음식에 대한 이야기',
                   'topic_eng': 'Talking about the most liked food'},
                  {'tag': 'C',
                   'topic_kor': '못 먹는 음식에 대한 이야기',
                   'topic_eng': 'Talking about foods one cannot eat'},
                  {'tag': 'C',
                   'topic_kor': '한국의 음식 문화에 대한 이야기',
                   'topic_eng': 'Discussing Korean food culture'},
                  {'tag': 'C',
                   'topic_kor': '본인의 주량에 대한 이야기',
                   'topic_eng': 'Talking about personal alcohol tolerance'},
                  {'tag': 'C',
                   'topic_kor': '좋아하는 술에 대한 이야기',
                   'topic_eng': 'Talking about favorite drinks'},
                  {'tag': 'C',
                   'topic_kor': '가고 싶은 여행지에 대한 이야기',
                   'topic_eng': 'Discussing desired travel destinations'},
                  {'tag': 'C',
                   'topic_kor': '계획 중인 여행에 대한 이야기',
                   'topic_eng': 'Discussing upcoming travel plans'},
                  {'tag': 'C',
                   'topic_kor': '첫 번째 해외 여행에 대한 이야기',
                   'topic_eng': 'Talking about the first overseas trip'},
                  {'tag': 'C',
                   'topic_kor': '여행 준비 노하우에 대한 이야기',
                   'topic_eng': 'Discussing travel preparation tips'},
                  {'tag': 'C',
                   'topic_kor': '여행 중 문화 차이를 느꼈던 에피소드에 대한 이야기',
                   'topic_eng': 'Talking about episodes of cultural differences during travel'},
                  {'tag': 'C',
                   'topic_kor': '음식 알러지에 대한 이야기',
                   'topic_eng': 'Talking about food allergies'},
                  {'tag': 'C',
                   'topic_kor': '좋아하는 디저트에 대한 이야기',
                   'topic_eng': 'Talking about favorite desserts'},
                  {'tag': 'C',
                   'topic_kor': '자신의 성격에 대한 이야기',
                   'topic_eng': 'Talking about personal characteristics'},
                  {'tag': 'C',
                   'topic_kor': '자신의 장점에 대한 이야기',
                   'topic_eng': 'Talking about personal strengths'},
                  {'tag': 'C',
                   'topic_kor': '자신의 단점에 대한 이야기',
                   'topic_eng': 'Talking about personal weaknesses'},
                  {'tag': 'C',
                   'topic_kor': '자신의 좋은 습관에 대한 이야기',
                   'topic_eng': 'Talking about good habits'},
                  {'tag': 'C',
                   'topic_kor': '자신의 좋지 않은 습관에 대한 이야기',
                   'topic_eng': 'Talking about bad habits'},
                  {'tag': 'C',
                   'topic_kor': '자신의 관심사에 대한 이야기',
                   'topic_eng': 'Talking about personal interests'},
                  {'tag': 'C',
                   'topic_kor': '자신의 특기에 대한 이야기',
                   'topic_eng': 'Talking about personal skills'},
                  {'tag': 'C',
                   'topic_kor': '자신이 어떤 사람이 되고 싶은지에 대한 이야기',
                   'topic_eng': 'Talking about the person one wants to become'},
                  {'tag': 'C',
                   'topic_kor': '최근에 갔던 전시회에 대한 이야기',
                   'topic_eng': 'Discussing recent exhibition visits'},
                  {'tag': 'C',
                   'topic_kor': '좋아하는 옷 스타일에 대한 이야기',
                   'topic_eng': 'Talking about favorite clothing styles'},
                  {'tag': 'C',
                   'topic_kor': '강아지를 좋아하는지 고양이를 좋아하는지에 대한 이야기',
                   'topic_eng': 'Discussing preference for dogs or cats'},
                  {'tag': 'C',
                   'topic_kor': '반려 동물과 관련된 행복했던 경험에 대한 이야기',
                   'topic_eng': 'Discussing happy experiences related to pets'},
                  {'tag': 'C',
                   'topic_kor': '반려 동물을 키웠던 경험에 대한 이야기',
                   'topic_eng': 'Talking about experiences of raising pets'},
                  {'tag': 'C',
                   'topic_kor': '한국의 길거리 음식에 대한 이야기',
                   'topic_eng': 'Talking about Korean street food'},
                  {'tag': 'C',
                   'topic_kor': '본인 나라의 길거리 음식 추천에 대한 이야기',
                   'topic_eng': "Discussing recommended street food in one's own country"},
                  {'tag': 'C',
                   'topic_kor': '한국의 배달 문화에 대한 이야기',
                   'topic_eng': 'Talking about Korean delivery culture'},
                  {'tag': 'C',
                   'topic_kor': '좋아하는 배달 음식에 대한 이야기',
                   'topic_eng': 'Talking about favorite delivery foods'},
                  {'tag': 'C',
                   'topic_kor': '최근 날씨에 대한 이야기',
                   'topic_eng': 'Discussing recent weather'},
                  {'tag': 'C',
                   'topic_kor': '좋아하는 계절에 대한 이야기',
                   'topic_eng': 'Talking about favorite seasons'},
                  {'tag': 'C',
                   'topic_kor': '최근에 유용하게 사용하고 있는 앱에 대한 이야기',
                   'topic_eng': 'Discussing useful apps used recently'},
                  {'tag': 'C',
                   'topic_kor': '자신의 전공에 대한 이야기',
                   'topic_eng': "Talking about one's major"},
                  {'tag': 'C',
                   'topic_kor': '자신이 전공을 선택한 이유에 대한 이야기',
                   'topic_eng': "Discussing reasons for choosing one's major"},
                  {'tag': 'C',
                   'topic_kor': '요리를 했던 경험에 대한 이야기',
                   'topic_eng': 'Talking about experiences of cooking'},
                  {'tag': 'C',
                   'topic_kor': '자신이 잘 하는 요리에 대한 이야기',
                   'topic_eng': 'Talking about dishes one is good at cooking'},
                  {'tag': 'C',
                   'topic_kor': '기억에 남는 선물에 대한 이야기',
                   'topic_eng': 'Talking about memorable gifts'},
                  {'tag': 'C',
                   'topic_kor': '가장 좋아하는 월(month)에 대한 이야기',
                   'topic_eng': 'Talking about the favorite month'},
                  {'tag': 'C',
                   'topic_kor': '지난 크리스마스에는 뭘 했는지에 대한 이야기',
                   'topic_eng': 'Talking about activities on the last Christmas'},
                  {'tag': 'C',
                   'topic_kor': '최근 자주 보는 유튜버에 대한 이야기',
                   'topic_eng': 'Talking about recent favorite YouTubers'},
                  {'tag': 'C',
                   'topic_kor': '최근 일주일 중 행복했던 순간에 대한 이야기',
                   'topic_eng': 'Talking about the happiest moment of the past week'},
                  {'tag': 'C',
                   'topic_kor': '고등학생 때 기억에 남는 경험에 대한 이야기',
                   'topic_eng': 'Talking about memorable high school experiences'},
                  {'tag': 'C',
                   'topic_kor': '자신의 고향에 대한 이야기',
                   'topic_eng': "Talking about one's hometown"},
                  {'tag': 'C',
                   'topic_kor': '어떤 일을 할 때 보람을 느끼는지에 대한 이야기',
                   'topic_eng': 'Talking about fulfilling activities'},
                  {'tag': 'C',
                   'topic_kor': '상대방의 첫인상을 음식으로 말해보기',
                   'topic_eng': 'Describing first impressions with food'},
                  {'tag': 'C',
                   'topic_kor': '팀 프로젝트가 좋은지, 개인 과제가 좋은지에 대한 이야기',
                   'topic_eng': 'Discussing team projects vs. individual assignments'},
                  {'tag': 'C',
                   'topic_kor': '본인 기준에 넘지 말아야 할 선에 대한 이야기',
                   'topic_eng': 'Discussing personal boundaries'},
                  {'tag': 'C',
                   'topic_kor': '다른 사람이 말하는 나와 내가 생각하는 나의 모습 중 가장 다른 부분에 대한 이야기',
                   'topic_eng': 'Talking about the most different aspect between how others see you and how you see yourself'},
                  {'tag': 'C',
                   'topic_kor': '자신이 좋아하는 날씨에 대한 이야기',
                   'topic_eng': "Talking about one's favorite weather"},
                  {'tag': 'C',
                   'topic_kor': '외로움을 느낄 때 자신이 하는 행동에 대한 이야기',
                   'topic_eng': 'Discussing actions taken when feeling lonely'},
                  {'tag': 'C',
                   'topic_kor': '여름에 겨울옷 입기 vs 겨울에 여름옷 입기',
                   'topic_eng': 'Summer clothes in winter vs. Winter clothes in summer'},
                  {'tag': 'C',
                   'topic_kor': '진정한 우정 vs 진정한 사랑',
                   'topic_eng': 'True friendship vs. True love'},
                  {'tag': 'C',
                   'topic_kor': '탄산 없는 콜라 vs 치즈 없는 피자',
                   'topic_eng': 'Cola without carbonation vs. Pizza without cheese'},
                  {'tag': 'C',
                   'topic_kor': '월급 500만원 직장인 vs 월급 200만원 백수',
                   'topic_eng': 'Monthly salary of 5 million KRW employee vs. Unemployed with a monthly salary of 2 million KRW'},
                  {'tag': 'C',
                   'topic_kor': '다른 사람이 하지 말았으면 하는 행동에 대한 이야기',
                   'topic_eng': 'Talking about actions others should not do'},
                  {'tag': 'C',
                   'topic_kor': '초능력을 하나 가질 수 있다면 갖고 싶은 초능력에 대한 이야기',
                   'topic_eng': 'Discussing the superpower one would want if given a choice'},
                  {'tag': 'C',
                   'topic_kor': '인스타 한달 금지 vs 유튜브 한달 금지',
                   'topic_eng': 'Instagram banned for a month vs. YouTube banned for a month'},
                  {'tag': 'C',
                   'topic_kor': '10년 뒤 본인의 모습에 대한 이야기',
                   'topic_eng': 'Talking about oneself 10 years from now'},
                  {'tag': 'C',
                   'topic_kor': '한 번 해 보고 싶은 아르바이트에 대한 이야기',
                   'topic_eng': 'Talking about part-time jobs one would like to try'},
                  {'tag': 'C',
                   'topic_kor': '자신의 아르바이트 경험에 대한 이야기',
                   'topic_eng': 'Discussing personal part-time job experiences'},
                  {'tag': 'C',
                   'topic_kor': '대학생활 중 가장 즐거웠던 경험에 대한 이야기',
                   'topic_eng': 'Discussing the most enjoyable experience during university life'},
                  {'tag': 'C',
                   'topic_kor': '대학생활 중 가장 힘들었던 경험에 대한 이야기',
                   'topic_eng': 'Discussing the most challenging experience during university life'},
                  {'tag': 'C',
                   'topic_kor': '좋아하는 색깔에 대한 이야기',
                   'topic_eng': 'Talking about favorite colors'},
                  {'tag': 'C',
                   'topic_kor': '5년 전으로 돌아갈 수 있다면 어떤 일을 할 것인가요?',
                   'topic_eng': 'If you could go back 5 years, what would you do?'},
                  {'tag': 'C',
                   'topic_kor': '자신의 별자리에 대한 이야기',
                   'topic_eng': "Talking about one's zodiac sign"},
                  {'tag': 'C',
                   'topic_kor': '자신의 징크스에 대한 이야기',
                   'topic_eng': 'Talking about personal jinxes'},
                  {'tag': 'C',
                   'topic_kor': '다른 동물로 태어날 수 있다면, 어떤 동물로 태어날 것인가요?',
                   'topic_eng': 'If you could be born as a different animal, what would it be?'},
                  {'tag': 'C',
                   'topic_kor': '내가 좋아하는 사람 만나기 vs 나를 좋아해주는 사람 만나기',
                   'topic_eng': 'Meeting someone you like vs. Meeting someone who likes you'},
                  {'tag': 'C',
                   'topic_kor': '자신의 술버릇에 대한 이야기',
                   'topic_eng': 'Talking about drinking habits'},
                  {'tag': 'C',
                   'topic_kor': '귀신을 봤던 경험에 대한 이야기',
                   'topic_eng': 'Discussing experiences of seeing ghosts'},
                  {'tag': 'C',
                   'topic_kor': '자신의 루틴에 대한 이야기',
                   'topic_eng': 'Talking about personal routines'},
                  {'tag': 'C',
                   'topic_kor': '최근에 했던 쇼핑에 대한 이야기',
                   'topic_eng': 'Talking about recent shopping experiences'},
                  {'tag': 'B',
                   'topic_kor': '가족과 가족 역사에 관한 이야기',
                   'topic_eng': 'Conversation about family and family history'},
                  {'tag': 'B',
                   'topic_kor': '산과 바다 중 어디를 더 좋아하는지?',
                   'topic_eng': 'Preference between mountains and the sea'},
                  {'tag': 'B',
                   'topic_kor': '집 주변 맛집에 대한 이야기',
                   'topic_eng': 'Conversation about favorite local restaurants'},
                  {'tag': 'B',
                   'topic_kor': '집 주변에서 산책할 만한 공원',
                   'topic_eng': 'Conversation about parks suitable for a stroll near home'},
                  {'tag': 'B',
                   'topic_kor': '연예인이 되고 싶다면 누가 되고 싶은지?',
                   'topic_eng': 'If you want to be a celebrity, who would you want to be?'},
                  {'tag': 'B',
                   'topic_kor': '단골 식당을 물어보기',
                   'topic_eng': 'Asking about favorite regular restaurants'},
                  {'tag': 'B',
                   'topic_kor': '시간을 돌릴 수 있다면 언제로 돌리고 싶은지',
                   'topic_eng': 'If you could turn back time, when would you want to go back?'},
                  {'tag': 'B',
                   'topic_kor': '어디로든 순간이동 초능력 vs 누구로든 변신가능 초능력',
                   'topic_eng': 'Teleportation ability to anywhere vs Shapeshifting ability to anyone'},
                  {'tag': 'B',
                   'topic_kor': '본인의 이상형에 대해 이야기하기',
                   'topic_eng': 'Talk about your ideal type'},
                  {'tag': 'B',
                   'topic_kor': '비건이나 채식주의자에 관한 경험에 대해 이야기하기',
                   'topic_eng': 'Share experiences about being a vegan or vegetarian'},
                  {'tag': 'B',
                   'topic_kor': '최신 AI 기술에 대해 이야기하기',
                   'topic_eng': 'Discuss the latest AI technology'},
                  {'tag': 'B',
                   'topic_kor': '평생 해산물 먹기 vs 평생 고기 먹기',
                   'topic_eng': 'Eating seafood for a lifetime vs Eating meat for a lifetime'},
                  {'tag': 'B',
                   'topic_kor': '자신의 가족에 대해 이야기하기',
                   'topic_eng': 'Talk about your family'},
                  {'tag': 'B',
                   'topic_kor': '팁 문화에 대한 생각 들어보기',
                   'topic_eng': 'Thoughts on tipping culture'},
                  {'tag': 'B',
                   'topic_kor': '한국의 저출산에 대한 이야기',
                   'topic_eng': 'Discussion about low birth rates in Korea'},
                  {'tag': 'B',
                   'topic_kor': '집값 상승에 대한 이야기',
                   'topic_eng': 'Conversation about rising home prices'},
                  {'tag': 'B',
                   'topic_kor': '자신의 재태크 경험에 대한 이야기',
                   'topic_eng': 'Talk about your investment experiences'},
                  {'tag': 'B',
                   'topic_kor': '아침형 인간인지, 저녁형 인간인지?',
                   'topic_eng': 'Are you a morning person or an evening person?'},
                  {'tag': 'B', 'topic_kor': '운명을 믿는지에 대한 이야기', 'topic_eng': 'Belief in fate'},
                  {'tag': 'B',
                   'topic_kor': '좋아하는 과일에 대한 이야기',
                   'topic_eng': 'Discussion about favorite fruits'},
                  {'tag': 'B',
                   'topic_kor': '하고 싶은 일과 해야 하는 일 중 어떤 것을 먼저 하는 편인가에 대한 이야기',
                   'topic_eng': 'Which comes first, what you want to do or what you have to do?'},
                  {'tag': 'B',
                   'topic_kor': '하고 싶은 일과 잘 하는 일 중 어떤 일을 하고 싶은 지에 대한 이야기',
                   'topic_eng': 'What you want to do vs What you are good at'},
                  {'tag': 'B',
                   'topic_kor': '한 달밖에 살 수 없다면, 무엇을 하고 싶은지에 대한 이야기',
                   'topic_eng': 'If you can only live for a month, what would you do?'},
                  {'tag': 'B',
                   'topic_kor': '세대 갈등에 대한 이야기',
                   'topic_eng': 'Generational conflicts'},
                  {'tag': 'B',
                   'topic_kor': '인생의 목표에 관한 이야기',
                   'topic_eng': 'Discussion about life goals'},
                  {'tag': 'B',
                   'topic_kor': '내 결혼식에 한 명도 안오기 vs 내 장례식에 한 명도 안오기',
                   'topic_eng': 'No one coming to your wedding vs No one coming to your funeral'},
                  {'tag': 'B',
                   'topic_kor': 'ChatGPT에 대한 생각',
                   'topic_eng': 'Thoughts on ChatGPT'},
                  {'tag': 'B',
                   'topic_kor': '인생에서의 돈의 중요성에 대한 생각',
                   'topic_eng': 'Thoughts on the importance of money in life'},
                  {'tag': 'B',
                   'topic_kor': '해 봤던 일 중 가장 미친 일에 대한 이야기',
                   'topic_eng': "Talk about the craziest thing you've ever done"},
                  {'tag': 'B',
                   'topic_kor': '졸업하고나서의 진로에 대한 이야기',
                   'topic_eng': 'Talk about post-graduation career plans'},
                  {'tag': 'B', 'topic_kor': '관심 있는 분야', 'topic_eng': 'Areas of interest'},
                  {'tag': 'B',
                   'topic_kor': '좋아하는 시간대는? 아침 vs 점심 vs 저녁 vs 새벽',
                   'topic_eng': 'Favorite time of the day: Morning vs Afternoon vs Evening vs Night'},
                  {'tag': 'B',
                   'topic_kor': '로또 당첨 vs 수명 2배',
                   'topic_eng': 'Lotto win vs Double lifespan'},
                  {'tag': 'B',
                   'topic_kor': '38도 여름 vs 영하 15도 겨울',
                   'topic_eng': '38-degree summer vs Minus 15-degree winter'},
                  {'tag': 'B',
                   'topic_kor': '15살로 평생살기 vs 50살로 평생살기',
                   'topic_eng': 'Live as a 15-year-old forever vs Live as a 50-year-old forever'},
                  {'tag': 'B',
                   'topic_kor': '평생 해산물 먹기 vs 평생 고기 먹기',
                   'topic_eng': 'Seafood for a lifetime vs Meat for a lifetime'},
                  {'tag': 'B',
                   'topic_kor': '자신이 느꼈던 문화 충격 이야기',
                   'topic_eng': 'Cultural shock experiences'},
                  {'tag': 'B',
                   'topic_kor': '각 나라의 역사에 대한 이야기',
                   'topic_eng': 'Stories about the history of each country'},
                  {'tag': 'B',
                   'topic_kor': '각 나라의 위인에 대한 이야기',
                   'topic_eng': 'Stories about notable figures in each country'},
                  {'tag': 'B',
                   'topic_kor': '각 나라의 지폐 속 위인 설명해 주기',
                   'topic_eng': "Explanations about figures on each country's currency"},
                  {'tag': 'B',
                   'topic_kor': '자신이 존경하는 위인에 대해 말해보기',
                   'topic_eng': 'Talk about someone you admire'},
                  {'tag': 'B',
                   'topic_kor': '환경오염에 대한 자신의 생각',
                   'topic_eng': 'Thoughts on environmental pollution'},
                  {'tag': 'B',
                   'topic_kor': '기후 변화에 대한 생각 말해보기',
                   'topic_eng': 'Thoughts on climate change'},
                  {'tag': 'B',
                   'topic_kor': '소득 양극화에 대한 생각 말해보기',
                   'topic_eng': 'Thoughts on income inequality'},
                  {'tag': 'B',
                   'topic_kor': '코로나 19때 겪었던 에피소드',
                   'topic_eng': 'Episodes during COVID-19'},
                  {'tag': 'B',
                   'topic_kor': '좋아하는 게임이 있는지?',
                   'topic_eng': 'Do you have a favorite game?'},
                  {'tag': 'B',
                   'topic_kor': '가장 좋아하는 외국 음식은?',
                   'topic_eng': 'Favorite foreign cuisine'},
                  {'tag': 'B',
                   'topic_kor': '자신만 아는 좋은 장소',
                   'topic_eng': 'A place only you know'},
                  {'tag': 'B',
                   'topic_kor': '일주일 내내 한 가지 음식만 먹어야 한다면?',
                   'topic_eng': 'If you could only eat one type of food for a week, what would it be?'},
                  {'tag': 'B',
                   'topic_kor': '오늘 어떤 하루를 보냈는지 공유하기',
                   'topic_eng': 'Share how your day went today'},
                  {'tag': 'B',
                   'topic_kor': '상대방의 첫인상과 달라서 놀랐던 부분에 대한 이야기',
                   'topic_eng': 'Talk about the first impression of someone that surprised you'},
                  {'tag': 'B',
                   'topic_kor': '어떤 동료와 일을 하고 싶나요? 능력은 좋지만 성격이 까칠한 A vs 성격은 좋지만 무능한 B',
                   'topic_eng': 'Who would you prefer to work with? Capable but grumpy A vs Friendly but incompetent B'},
                  {'tag': 'B',
                   'topic_kor': '서로에게 칭찬할 점',
                   'topic_eng': 'Compliments for each other'},
                  {'tag': 'B',
                   'topic_kor': '혼자 여행을 가 본 경험',
                   'topic_eng': 'Experience of traveling alone'},
                  {'tag': 'B',
                   'topic_kor': 'SNS를 하는지? SNS를 활발히 하는 것에 대한 자신의 생각',
                   'topic_eng': 'Do you use social media? Thoughts on being active on social media'},
                  {'tag': 'B',
                   'topic_kor': '자신이 관심 있는 과학 분야에 대한 이야기',
                   'topic_eng': 'Talk about your interest in scientific fields'},
                  {'tag': 'B',
                   'topic_kor': '자신의 소비 패턴 중 가장 큰 부분을 차지하는 분야',
                   'topic_eng': 'Which area occupies the largest part of your consumption pattern?'},
                  {'tag': 'B',
                   'topic_kor': '요즘하고 있는 고민에 대한 이야기',
                   'topic_eng': 'Current concerns'},
                  {'tag': 'B',
                   'topic_kor': '상대방의 국가와 관련된 재밌는 경험 공유하기',
                   'topic_eng': "Share interesting experiences related to the partner's country"},
                  {'tag': 'B',
                   'topic_kor': '상대방의 언어를 배우면서 어려웠던 점',
                   'topic_eng': "Difficulties in learning the partner's language"},
                  {'tag': 'B',
                   'topic_kor': '외국인 친구를 사귀면 해 보고 싶었던 활동',
                   'topic_eng': 'Activity you wanted to try when making friends with a foreigner'},
                  {'tag': 'B',
                   'topic_kor': '한국에 관심을 갖게 된 이유',
                   'topic_eng': 'Reasons for being interested in Korea'},
                  {'tag': 'B',
                   'topic_kor': '한국 문화 중 가장 마음에 드는 것',
                   'topic_eng': 'Favorite aspect of Korean culture'},
                  {'tag': 'B',
                   'topic_kor': '자신의 버킷리스트에 대해 말해보기',
                   'topic_eng': 'Talk about your bucket list'},
                  {'tag': 'B',
                   'topic_kor': '남자사람친구 또는 여자사람친구의 진정한 우정이 가능하다고 생각하는지',
                   'topic_eng': 'Do you believe true friendship between a man and a woman is possible?'},
                  {'tag': 'B',
                   'topic_kor': '자신이 했던 동아리에 대해 이야기해보기',
                   'topic_eng': 'Talk about the club you were involved in'},
                  {'tag': 'B',
                   'topic_kor': '놀이공원을 갔던 경험 이야기하기',
                   'topic_eng': 'Experience of going to an amusement park'},
                  {'tag': 'B',
                   'topic_kor': '최근에 꿨던 꿈 이야기하기',
                   'topic_eng': 'Share a recent dream'},
                  {'tag': 'B',
                   'topic_kor': '일주일 간 일어났던 일 중 한 가지를 바꿀 수 있다면',
                   'topic_eng': 'If you could change one thing that happened in the past week'},
                  {'tag': 'B',
                   'topic_kor': '진로를 결정할 때 가장 중요하게 생각하는 것은 무엇인지',
                   'topic_eng': 'What is most important to you when deciding a career path?'},
                  {'tag': 'B',
                   'topic_kor': '커리어와 가정 중 어떤 것이 더 중요하다고 생각하는지',
                   'topic_eng': 'Which is more important, career or family?'},
                  {'tag': 'B',
                   'topic_kor': '처음 보는 상대방과 금방 친해지는 법에 대한 이야기',
                   'topic_eng': 'How to quickly become close with someone you just met'},
                  {'tag': 'B',
                   'topic_kor': '짝사랑했던 경험에 대한 이야기',
                   'topic_eng': 'Experience of having a crush'},
                  {'tag': 'B',
                   'topic_kor': '나중에 어떤 나라에서 살고 싶은지',
                   'topic_eng': 'Which country would you like to live in later?'},
                  {'tag': 'B',
                   'topic_kor': '친구와 싸웠던 경험에 대한 이야기',
                   'topic_eng': 'Experience of fighting with a friend'},
                  {'tag': 'B',
                   'topic_kor': '친구가 자신을 서운하게 했던 경험에 대한 이야기',
                   'topic_eng': 'Experience of being hurt by a friend'},
                  {'tag': 'B',
                   'topic_kor': '다른 전공을 선택할 수 있다면 선택하고 싶은 전공',
                   'topic_eng': 'If you could choose a different major, what would it be?'},
                  {'tag': 'B',
                   'topic_kor': '자신의 외모 중 한 가지를 바꿀 수 있다면 어느 곳을 바꾸고 싶은지',
                   'topic_eng': 'If you could change one thing about your appearance, where would you change?'},
                  {'tag': 'B',
                   'topic_kor': '요즘 가장 스트레스를 주는 일이 무엇인지',
                   'topic_eng': 'What is currently causing you the most stress?'},
                  {'tag': 'B',
                   'topic_kor': '언제 행복을 느끼는지',
                   'topic_eng': 'When do you feel happy?'},
                  {'tag': 'B',
                   'topic_kor': '인생에서 가장 슬펐던 경험은 무엇인지',
                   'topic_eng': 'What was the saddest experience in your life?'},
                  {'tag': 'B',
                   'topic_kor': '가장 좋아하는 악기는 무엇인지',
                   'topic_eng': 'Favorite musical instrument'},
                  {'tag': 'B',
                   'topic_kor': '인생의 최종적인 목표가 무엇인지',
                   'topic_eng': 'Ultimate goal in life'},
                  {'tag': 'B',
                   'topic_kor': '깊고 좁은 인간관계 vs 넓고 얕은 인간관계',
                   'topic_eng': 'Deep and narrow human relationships vs Wide and shallow human relationships'},
                  {'tag': 'B',
                   'topic_kor': '친구와 단 둘이 만나는 걸 좋아하는지, 여러 명이 만나는 걸 좋아하는지',
                   'topic_eng': 'Prefer meeting with just one or meeting with many friends'},
                  {'tag': 'B',
                   'topic_kor': '예전부터 꿈꿔 왔지만 용기가 없어 하지 못한 일이 있는지',
                   'topic_eng': "Is there something you've always dreamed of but haven't had the courage to do?"},
                  {'tag': 'B',
                   'topic_kor': '친구를 만나면 보통 어떤 활동을 하는지',
                   'topic_eng': 'What activities do you usually do when meeting friends?'},
                  {'tag': 'B',
                   'topic_kor': '사람을 만났을 때 말을 하는 편인지, 말을 들어주는 편인지',
                   'topic_eng': 'Are you more of a talker or a listener when meeting people?'},
                  {'tag': 'B',
                   'topic_kor': '응원하는 스포츠 팀이 있는 지',
                   'topic_eng': 'Do you have a sports team you support?'},
                  {'tag': 'B',
                   'topic_kor': '자신이 생각하는 한국의 매력',
                   'topic_eng': 'What do you find charming about Korea?'},
                  {'tag': 'B',
                   'topic_kor': '누군가 자신의 아이디어를 가로챘을 때의 대처',
                   'topic_eng': 'How do you react if someone takes your idea?'},
                  {'tag': 'B',
                   'topic_kor': '영화와 TV 프로그램과 관련된 최근 이슈에 대한 이야기',
                   'topic_eng': 'Recent issues related to movies and TV programs'},
                  {'tag': 'B',
                   'topic_kor': '사회적 책임감 및 봉사 활동을 통한 사회 기여에 관한 관심사에 관한 대화',
                   'topic_eng': 'Discussion about social responsibility and contributions through volunteer activities'},
                  {'tag': 'B',
                   'topic_kor': '음악 분야와 음악 산업 관련 주제에 대한 토론',
                   'topic_eng': 'Debate on topics related to the music field and the music industry'},
                  {'tag': 'B',
                   'topic_kor': '인류학과 문화 사회학에서의 연구 주제와 이론에 관한 이야기',
                   'topic_eng': 'Talk about research topics and theories in anthropology and cultural sociology'},
                  {'tag': 'A',
                   'topic_kor': '자신의 인생의 목표와 비전에 대한 이야기',
                   'topic_eng': 'Conversation about the ultimate goal in life'},
                  {'tag': 'A',
                   'topic_kor': '자신의 가치관과 신념에 대한 대화',
                   'topic_eng': "Conversation about one's beliefs"},
                  {'tag': 'A',
                   'topic_kor': '현대 청소년들의 윤리의식 결여에 관한 이야기',
                   'topic_eng': 'Discussion on the lack of ethical awareness among modern teenagers'},
                  {'tag': 'A',
                   'topic_kor': '미디어의 이용이 인간의 지능에 미치는 영향에 대한 이야기',
                   'topic_eng': 'Conversation about the impact of media usage on human intelligence'},
                  {'tag': 'A',
                   'topic_kor': '한국의 초전도체 이슈에 관한 이야기',
                   'topic_eng': 'Discussion on the issue of room temperature superconductors in Korea'},
                  {'tag': 'A',
                   'topic_kor': '정신건강과 관련한 자기의 경험에 대한 이야기',
                   'topic_eng': 'Conversation about personal experiences related to mental health'},
                  {'tag': 'A',
                   'topic_kor': '인생을 살아오며 있었던 역경과 그로 인한 성장에 관한 대화',
                   'topic_eng': 'Conversation about the hardships faced in life and the growth resulting from them'},
                  {'tag': 'A',
                   'topic_kor': '명상에 대한 실효성 논의',
                   'topic_eng': 'Conversation about the effectiveness of meditation'},
                  {'tag': 'A',
                   'topic_kor': '이해하기 어려운 현대예술에 관한 이야기',
                   'topic_eng': 'Discussion on the complexity of modern art'},
                  {'tag': 'A',
                   'topic_kor': '자기계발과 자기 완성에 관한 비전, 목표에 대한 이야기',
                   'topic_eng': 'Conversation about vision and goals related to self-development and self-completion'},
                  {'tag': 'A',
                   'topic_kor': '어른이 되고 나서 했던 사회 봉사 경험과 느낀 점에대한 이야기',
                   'topic_eng': 'Conversation about social service experiences and reflections after becoming an adult'},
                  {'tag': 'A',
                   'topic_kor': '철학적 사색이 현대인에게 주는 실질적인 도움에 관한 이야기',
                   'topic_eng': 'Discussion on the practical help of philosophical contemplation for modern individuals'},
                  {'tag': 'A',
                   'topic_kor': '20세기에 있었던 역사적 사건 중 가장 중요하다고 생각하는 사건에 대한 이야기',
                   'topic_eng': "Conversation about the most important historical event in the 20th century, in one's opinion"},
                  {'tag': 'A',
                   'topic_kor': '유전공학이 발달함에 따른 부작용에 대한 이야기',
                   'topic_eng': 'Conversation about the side effects of genetic engineering'},
                  {'tag': 'A',
                   'topic_kor': '자기 나라의 정치이슈와 본인이 바라는 국제관계에 대한 대화',
                   'topic_eng': "Discussion on one's country's political issues and desired international relations"},
                  {'tag': 'A',
                   'topic_kor': '자신이 공부하고 있는 학문의 연구 주제에 관한 이야기',
                   'topic_eng': 'Conversation about the research topic in the academic field one is studying'},
                  {'tag': 'A',
                   'topic_kor': '연예인은 공인인가에 대한 토론',
                   'topic_eng': 'Debate on whether celebrities are public figures'},
                  {'tag': 'A',
                   'topic_kor': '자신의 나라가 가진 세계문화유산에 대한 이야기',
                   'topic_eng': "Conversation about the world cultural heritage of one's own country"},
                  {'tag': 'A',
                   'topic_kor': '각자의 나라의 교육정책이 가진 특징과 문제점에 대한 이야기',
                   'topic_eng': 'Conversation about the characteristics and issues of education policies in each country'},
                  {'tag': 'A',
                   'topic_kor': '음악과 예술의 역할과 예술가의 가치에 대한 이야기',
                   'topic_eng': 'Conversation about the role of music and art and the value of artists'},
                  {'tag': 'A',
                   'topic_kor': '한국의 경제문제와 이를 타개할 방안에 대한 토론',
                   'topic_eng': 'Discussion on economic issues in Korea and possible solutions'},
                  {'tag': 'A',
                   'topic_kor': '자연과 지구 환경 보호의 필요성에 관한 대화',
                   'topic_eng': 'Conversation about the necessity of nature and environmental protection'},
                  {'tag': 'A',
                   'topic_kor': '세계의 독특한 문화와 관습에 대한 본인의 생각',
                   'topic_eng': 'Personal thoughts on the unique cultures and customs around the world'},
                  {'tag': 'A',
                   'topic_kor': '전쟁무기 등 과학기술 분야에서의 윤리적 고민에 관한 토론',
                   'topic_eng': 'Discussion on ethical considerations in the field of science and technology, especially in weapons'},
                  {'tag': 'A',
                   'topic_kor': '지속 가능한 기술, 미래에 관한 이야기',
                   'topic_eng': 'Conversation about sustainable technology and discussions about the future'},
                  {'tag': 'A',
                   'topic_kor': '역사적인 인물을 통해 배우는 교훈에 대한 이야기',
                   'topic_eng': 'Conversation about lessons learned through historical figures'},
                  {'tag': 'A',
                   'topic_kor': '천문학 및 우주에 대한 이야기',
                   'topic_eng': 'Conversation about astronomy and the universe'},
                  {'tag': 'A',
                   'topic_kor': '각자의 나라에서 사회운동, 학생운동 등의 동향',
                   'topic_eng': 'Trends in social movements, student movements, etc., in each country'},
                  {'tag': 'A',
                   'topic_kor': '인생의 의미와 삶을 대하는 자세에 대한 이야기',
                   'topic_eng': "Conversation about the meaning of life and one's attitude towards it"},
                  {'tag': 'A',
                   'topic_kor': '감명깊게 보았던 예술 및 문학에서의 고전작품에 대한 이야기',
                   'topic_eng': 'Conversation about classic works of art and literature that deeply impacted the individual'},
                  {'tag': 'A',
                   'topic_kor': '이상적인 정치 및 정부 체제에 관한 깊은 토론',
                   'topic_eng': 'In-depth discussion on the ideal political and government system'},
                  {'tag': 'A',
                   'topic_kor': '건강 및 복지에서 정부의 개입범위에 대한 이야기',
                   'topic_eng': "Conversation about the government's intervention in health and welfare"},
                  {'tag': 'A',
                   'topic_kor': '지구와 환경 보호를 위한 개인적인 노력에 대한 이야기',
                   'topic_eng': 'Conversation about personal efforts for earth and environmental protection'},
                  {'tag': 'A',
                   'topic_kor': '사회문제를 해결하기 위해 할 수 있는 개인의 역할에 대한 이야기',
                   'topic_eng': "Conversation about the individual's role in solving social problems"},
                  {'tag': 'A',
                   'topic_kor': '현대사회에서 심리 치료의 중요성이 증가하는 이유에 대한 이야기',
                   'topic_eng': 'Conversation about the increasing importance of psychological therapy in modern society'},
                  {'tag': 'A',
                   'topic_kor': '다문화 추세와 함께 이를 포용하는 방법에 관한 토론',
                   'topic_eng': 'Discussion on embracing multiculturalism and ways to do so'},
                  {'tag': 'A',
                   'topic_kor': '인류가 지금보다 더 발전할 수 있을 지에 대한 논의',
                   'topic_eng': 'Discussion on whether humanity can progress beyond its current state'},
                  {'tag': 'A',
                   'topic_kor': '과학기술의 발달에 따른 인간소외 현상에 대한 이야기',
                   'topic_eng': 'Conversation about the alienation caused by the development of science and technology'},
                  {'tag': 'A',
                   'topic_kor': '각자가 경험했던 수면장애와 그 해소법에 대한 이야기',
                   'topic_eng': 'Conversation about personal experiences with sleep disorders and their resolutions'},
                  {'tag': 'A',
                   'topic_kor': '세계 정치와 국제 관계의 동향과 전쟁가능성에 관한 대화',
                   'topic_eng': 'Discussion on the global political trends and the possibility of war'},
                  {'tag': 'A',
                   'topic_kor': '문학작품을 통해 얻은 개인적 변화에 대한 이야기',
                   'topic_eng': 'Conversation about personal transformation through literary works'},
                  {'tag': 'A',
                   'topic_kor': '국가가 지켜주어야 할 인권의 범위와 사회정의에 대한 이야기',
                   'topic_eng': 'Discussion on the scope of human rights that a nation should guarantee and social justice'},
                  {'tag': 'A',
                   'topic_kor': '정책 결정에 영향을 미치는 경제 주체들이 주는 부정적 영향에 대한 이야기',
                   'topic_eng': 'Conversation about the negative impact of economic entities on policy decisions'},
                  {'tag': 'A',
                   'topic_kor': '건강관리를 위해 하고 있는 노력에 대한 이야기',
                   'topic_eng': 'Conversation about efforts for health management'},
                  {'tag': 'A',
                   'topic_kor': '지구 온난화로 인해 발생하는 문제를 보상할 방법에 대한 이야기',
                   'topic_eng': 'Conversation about addressing issues arising from global warming'},
                  {'tag': 'A',
                   'topic_kor': '민주주의, 사회주의 등 정치체제에 관한 토론',
                   'topic_eng': 'Debate on political systems like democracy, socialism, etc.'},
                  {'tag': 'A',
                   'topic_kor': '자신의 나라가 가진 인터넷 문화와 개인적인 평가',
                   'topic_eng': "Individual assessment of internet culture in one's own country"},
                  {'tag': 'A',
                   'topic_kor': '가축과 반려동물에 대한 인간의 태도 차이에 대한 토론',
                   'topic_eng': 'Debate on differences in human attitudes towards livestock and pets'},
                  {'tag': 'A',
                   'topic_kor': '자신이 가진 언어 공부에 대한 노하우',
                   'topic_eng': 'Tips for language study one has'},
                  {'tag': 'A',
                   'topic_kor': '과학 연구자가 가져야 하는 윤리의식에 대한 이야기',
                   'topic_eng': 'Conversation about the ethical consciousness scientists should have'},
                  {'tag': 'A',
                   'topic_kor': '사회적 평등이 어느정도까지 보장되어야 하는 지에 대한 이야기',
                   'topic_eng': 'Conversation about how much social equality should be guaranteed'},
                  {'tag': 'A',
                   'topic_kor': '예술가의 가치 평가가 경제적으로 이루어지는 현상에 대한 이야기',
                   'topic_eng': 'Conversation about the economic evaluation of artists in the phenomenon of art'},
                  {'tag': 'A',
                   'topic_kor': '정치가 실질적으로 국민의 삶에 영향을 미치는 가에 대한 토론',
                   'topic_eng': 'Debate on the practical influence of politicians on the lives of citizens'},
                  {'tag': 'A',
                   'topic_kor': '이웃 나라에 일으킨 환경 문제를 보전해줄 정치적 해결 방법에 대한 토론',
                   'topic_eng': 'Discussion on political solutions to environmental issues caused by neighboring countries'},
                  {'tag': 'A',
                   'topic_kor': '자국의 재활용 및 분리수거 실태와 그 효용성에 대한 이야기',
                   'topic_eng': "Conversation about the current status and utility of recycling and waste separation in one's own country"},
                  {'tag': 'A',
                   'topic_kor': '소셜미디어의 성장이 가져온 부정적인 사회영향에 대한 이야기',
                   'topic_eng': 'Conversation about the negative social impact of the growth of social media'},
                  {'tag': 'A',
                   'topic_kor': '소득불평등을 해소하기 위한 자국 정부의 다양한 노력에 대한 이야기',
                   'topic_eng': "Conversation about efforts by one's own government to address income inequality"},
                  {'tag': 'A',
                   'topic_kor': 'K-POP의 성장 요인에 대한 토론',
                   'topic_eng': 'Debate on the factors contributing to the growth of K-POP'},
                  {'tag': 'A',
                   'topic_kor': '동아시아 각 국의 정치적 특징과 장, 단점에 대한 이야기',
                   'topic_eng': 'Discussion on the political characteristics of each East Asian country, their strengths, and weaknesses'},
                  {'tag': 'A',
                   'topic_kor': '최근에 겪어보았던 건강 문제와 해소하기 위한 노력에 대한 이야기',
                   'topic_eng': 'Conversation about recent health issues experienced and efforts to address them'},
                  {'tag': 'A',
                   'topic_kor': '지속 가능한 에너지솔루션이 유발하는 선진국과 개도국 간 격차에 대한 이야기',
                   'topic_eng': 'Discussion on the gap between advanced and developing countries caused by sustainable energy solutions'},
                  {'tag': 'A',
                   'topic_kor': '삶을 의미있게 하는 요소(가족, 물질적 풍요, 직업적 성취 등)에 대한 이야기',
                   'topic_eng': 'Conversation about elements that give meaning to life (family, material prosperity, occupational achievements, etc.)'},
                  {'tag': 'A',
                   'topic_kor': '가정과 일의 균형을 맞추기 위해 가장 중요한 부분에 대한 토론',
                   'topic_eng': 'Debate on the most important aspect of balancing family and work'},
                  {'tag': 'A',
                   'topic_kor': '본인이 생각하는 인생에서의 핵심 가치와 이를 이루기 위한 노력에 대한 이야기',
                   'topic_eng': "Conversation about one's core values in life and efforts to achieve them"},
                  {'tag': 'A',
                   'topic_kor': '묻지마 범죄가 증가하는 현상과 해결방안에 대한 이야기',
                   'topic_eng': 'Conversation about addressing the growing phenomenon of crime and solutions'},
                  {'tag': 'A',
                   'topic_kor': '한국의 심각한 저출산과 그 요인에 대한 토론',
                   'topic_eng': 'Debate on the serious issue of low birth rates in Korea and its factors'},
                  {'tag': 'A',
                   'topic_kor': '가장 독특하다고 생각되었던 타 국의 문화에 대한 이야기',
                   'topic_eng': 'Conversation about the most unique cultural aspects of other countries'},
                  {'tag': 'A',
                   'topic_kor': '음주와 흡연의 유해성과 정부 정책적인 해결방안에 대한 이야기',
                   'topic_eng': 'Conversation about the harmful effects of alcohol and smoking and government policy solutions'},
                  {'tag': 'A',
                   'topic_kor': '자신이 생각하는 바람직한 가족상에 대한 이야기',
                   'topic_eng': "Conversation about one's ideal family and its characteristics"},
                  {'tag': 'A',
                   'topic_kor': '전쟁가능성이 높아지고 있는 국가의 핵개발은 정당한가에 관한 토론',
                   'topic_eng': 'Debate on the legitimacy of nuclear development in countries with a high possibility of war'},
                  {'tag': 'A',
                   'topic_kor': '보편적 복지와 선별적 복지의 효율성에 대한 토론',
                   'topic_eng': 'Discussion on the efficiency of universal welfare and selective welfare'},
                  {'tag': 'A',
                   'topic_kor': '니트족, 프리터족과 같은 사회현상의 해결 방법에 대한 이야기',
                   'topic_eng': "Conversation about addressing social phenomena like 'N-kids' and 'F-kids'"},
                  {'tag': 'A',
                   'topic_kor': '횡재세(windfall tax) 도입에 대한 자신의 견해 이야기',
                   'topic_eng': "Conversation about one's opinion on the introduction of a windfall tax"}]

    op.bulk_insert(topic, topic_data)


def downgrade() -> None:
    meta = sa.MetaData()
    meta.reflect(only=('topic',), bind=op.get_bind())
    topic_tbl = sa.Table('topic', meta)
    op.get_bind().execute(topic_tbl.delete())
    with op.batch_alter_table("topic") as alter_table_topic_op:
        alter_table_topic_op.add_column(
            sa.Column('topic', sa.String(), nullable=False)
        )
        alter_table_topic_op.add_column(
            sa.Column('is_korean', sa.BOOLEAN(), server_default=sa.true())
        )
        alter_table_topic_op.drop_column("topic_eng")
        alter_table_topic_op.drop_column("topic_kor")

    topic_data = [
        {
            "topic": "Conversation about the ultimate goal in life",
            "tag": "A",
            "is_korean": False,
        },
        {"topic": "Conversation about one's beliefs", "tag": "A", "is_korean": False},
        {
            "topic": "Discussion on the lack of ethical awareness among modern teenagers",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about the impact of media usage on human intelligence",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Discussion on the issue of room temperature superconductors in Korea",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about personal experiences related to mental health",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about the hardships faced in life and the growth resulting from them",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about the effectiveness of meditation",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Discussion on the complexity of modern art",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about vision and goals related to self-development and self-completion",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about social service experiences and reflections after becoming an adult",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Discussion on the practical help of philosophical contemplation for modern individuals",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about the most important historical event in the 20th century, in one's opinion",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about the side effects of genetic engineering",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Discussion on one's country's political issues and desired international relations",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about the research topic in the academic field one is studying",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Debate on whether celebrities are public figures",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about the world cultural heritage of one's own country",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about the characteristics and issues of education policies in each country",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about the role of music and art and the value of artists",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Discussion on economic issues in Korea and possible solutions",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about the necessity of nature and environmental protection",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Personal thoughts on the unique cultures and customs around the world",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Discussion on ethical considerations in the field of science and technology, especially in weapons",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about sustainable technology and discussions about the future",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about lessons learned through historical figures",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about astronomy and the universe",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Trends in social movements, student movements, etc., in each country",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about the meaning of life and one's attitude towards it",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about classic works of art and literature that deeply impacted the individual",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "In-depth discussion on the ideal political and government system",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about the government's intervention in health and welfare",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about personal efforts for earth and environmental protection",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about the individual's role in solving social problems",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about the increasing importance of psychological therapy in modern society",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Discussion on embracing multiculturalism and ways to do so",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Discussion on whether humanity can progress beyond its current state",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about the alienation caused by the development of science and technology",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about personal experiences with sleep disorders and their resolutions",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Discussion on the global political trends and the possibility of war",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about personal transformation through literary works",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Discussion on the scope of human rights that a nation should guarantee and social justice",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about the negative impact of economic entities on policy decisions",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about efforts for health management",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about addressing issues arising from global warming",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Debate on political systems like democracy, socialism, etc.",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Individual assessment of internet culture in one's own country",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Debate on differences in human attitudes towards livestock and pets",
            "tag": "A",
            "is_korean": False,
        },
        {"topic": "Tips for language study one has", "tag": "A", "is_korean": False},
        {
            "topic": "Conversation about the ethical consciousness scientists should have",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about how much social equality should be guaranteed",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about the economic evaluation of artists in the phenomenon of art",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Debate on the practical influence of politicians on the lives of citizens",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Discussion on political solutions to environmental issues caused by neighboring countries",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about the current status and utility of recycling and waste separation in one's own country",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about the negative social impact of the growth of social media",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about efforts by one's own government to address income inequality",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Debate on the factors contributing to the growth of K-POP",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Discussion on the political characteristics of each East Asian country, their strengths, and weaknesses",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about recent health issues experienced and efforts to address them",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Discussion on the gap between advanced and developing countries caused by sustainable energy solutions",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about elements that give meaning to life (family, material prosperity, occupational achievements, etc.)",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Debate on the most important aspect of balancing family and work",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about one's core values in life and efforts to achieve them",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about addressing the growing phenomenon of crime and solutions",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Debate on the serious issue of low birth rates in Korea and its factors",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about the most unique cultural aspects of other countries",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about the harmful effects of alcohol and smoking and government policy solutions",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about one's ideal family and its characteristics",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Debate on the legitimacy of nuclear development in countries with a high possibility of war",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Discussion on the efficiency of universal welfare and selective welfare",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about addressing social phenomena like 'N-kids' and 'F-kids'",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about one's opinion on the introduction of a windfall tax",
            "tag": "A",
            "is_korean": False,
        },
        {
            "topic": "Conversation about family and family history",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Preference between mountains and the sea",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Conversation about favorite local restaurants",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Conversation about parks suitable for a stroll near home",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "If you want to be a celebrity, who would you want to be?",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Asking about favorite regular restaurants",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "If you could turn back time, when would you want to go back?",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Teleportation ability to anywhere vs Shapeshifting ability to anyone",
            "tag": "B",
            "is_korean": False,
        },
        {"topic": "Talk about your ideal type", "tag": "B", "is_korean": False},
        {
            "topic": "Share experiences about being a vegan or vegetarian",
            "tag": "B",
            "is_korean": False,
        },
        {"topic": "Discuss the latest AI technology", "tag": "B", "is_korean": False},
        {
            "topic": "Eating seafood for a lifetime vs Eating meat for a lifetime",
            "tag": "B",
            "is_korean": False,
        },
        {"topic": "Talk about your family", "tag": "B", "is_korean": False},
        {"topic": "Thoughts on tipping culture", "tag": "B", "is_korean": False},
        {
            "topic": "Discussion about low birth rates in Korea",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Conversation about rising home prices",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Talk about your investment experiences",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Are you a morning person or an evening person?",
            "tag": "B",
            "is_korean": False,
        },
        {"topic": "Belief in fate", "tag": "B", "is_korean": False},
        {"topic": "Discussion about favorite fruits", "tag": "B", "is_korean": False},
        {
            "topic": "Which comes first, what you want to do or what you have to do?",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "What you want to do vs What you are good at",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "If you can only live for a month, what would you do?",
            "tag": "B",
            "is_korean": False,
        },
        {"topic": "Generational conflicts", "tag": "B", "is_korean": False},
        {"topic": "Discussion about life goals", "tag": "B", "is_korean": False},
        {
            "topic": "No one coming to your wedding vs No one coming to your funeral",
            "tag": "B",
            "is_korean": False,
        },
        {"topic": "Thoughts on ChatGPT", "tag": "B", "is_korean": False},
        {
            "topic": "Thoughts on the importance of money in life",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Talk about the craziest thing you've ever done",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Talk about post-graduation career plans",
            "tag": "B",
            "is_korean": False,
        },
        {"topic": "Areas of interest", "tag": "B", "is_korean": False},
        {
            "topic": "Favorite time of the day: Morning vs Afternoon vs Evening vs Night",
            "tag": "B",
            "is_korean": False,
        },
        {"topic": "Lotto win vs Double lifespan", "tag": "B", "is_korean": False},
        {
            "topic": "38-degree summer vs Minus 15-degree winter",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Live as a 15-year-old forever vs Live as a 50-year-old forever",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Seafood for a lifetime vs Meat for a lifetime",
            "tag": "B",
            "is_korean": False,
        },
        {"topic": "Cultural shock experiences", "tag": "B", "is_korean": False},
        {
            "topic": "Stories about the history of each country",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Stories about notable figures in each country",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Explanations about figures on each country's currency",
            "tag": "B",
            "is_korean": False,
        },
        {"topic": "Talk about someone you admire", "tag": "B", "is_korean": False},
        {
            "topic": "Thoughts on environmental pollution",
            "tag": "B",
            "is_korean": False,
        },
        {"topic": "Thoughts on climate change", "tag": "B", "is_korean": False},
        {"topic": "Thoughts on income inequality", "tag": "B", "is_korean": False},
        {"topic": "Episodes during COVID-19", "tag": "B", "is_korean": False},
        {"topic": "Do you have a favorite game?", "tag": "B", "is_korean": False},
        {"topic": "Favorite foreign cuisine", "tag": "B", "is_korean": False},
        {"topic": "A place only you know", "tag": "B", "is_korean": False},
        {
            "topic": "If you could only eat one type of food for a week, what would it be?",
            "tag": "B",
            "is_korean": False,
        },
        {"topic": "Share how your day went today", "tag": "B", "is_korean": False},
        {
            "topic": "Talk about the first impression of someone that surprised you",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Who would you prefer to work with? Capable but grumpy A vs Friendly but incompetent B",
            "tag": "B",
            "is_korean": False,
        },
        {"topic": "Compliments for each other", "tag": "B", "is_korean": False},
        {"topic": "Experience of traveling alone", "tag": "B", "is_korean": False},
        {
            "topic": "Do you use social media? Thoughts on being active on social media",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Talk about your interest in scientific fields",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Which area occupies the largest part of your consumption pattern?",
            "tag": "B",
            "is_korean": False,
        },
        {"topic": "Current concerns", "tag": "B", "is_korean": False},
        {
            "topic": "Share interesting experiences related to the partner's country",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Difficulties in learning the partner's language",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Activity you wanted to try when making friends with a foreigner",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Reasons for being interested in Korea",
            "tag": "B",
            "is_korean": False,
        },
        {"topic": "Favorite aspect of Korean culture", "tag": "B", "is_korean": False},
        {"topic": "Talk about your bucket list", "tag": "B", "is_korean": False},
        {
            "topic": "Do you believe true friendship between a man and a woman is possible?",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Talk about the club you were involved in",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Experience of going to an amusement park",
            "tag": "B",
            "is_korean": False,
        },
        {"topic": "Share a recent dream", "tag": "B", "is_korean": False},
        {
            "topic": "If you could change one thing that happened in the past week",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "What is most important to you when deciding a career path?",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Which is more important, career or family?",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "How to quickly become close with someone you just met",
            "tag": "B",
            "is_korean": False,
        },
        {"topic": "Experience of having a crush", "tag": "B", "is_korean": False},
        {
            "topic": "Which country would you like to live in later?",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Experience of fighting with a friend",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Experience of being hurt by a friend",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "If you could choose a different major, what would it be?",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "If you could change one thing about your appearance, where would you change?",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "What is currently causing you the most stress?",
            "tag": "B",
            "is_korean": False,
        },
        {"topic": "When do you feel happy?", "tag": "B", "is_korean": False},
        {
            "topic": "What was the saddest experience in your life?",
            "tag": "B",
            "is_korean": False,
        },
        {"topic": "Favorite musical instrument", "tag": "B", "is_korean": False},
        {"topic": "Ultimate goal in life", "tag": "B", "is_korean": False},
        {
            "topic": "Deep and narrow human relationships vs Wide and shallow human relationships",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Prefer meeting with just one or meeting with many friends",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Is there something you've always dreamed of but haven't had the courage to do?",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "What activities do you usually do when meeting friends?",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Are you more of a talker or a listener when meeting people?",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Do you have a sports team you support?",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "What do you find charming about Korea?",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "How do you react if someone takes your idea?",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Recent issues related to movies and TV programs",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Discussion about social responsibility and contributions through volunteer activities",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Debate on topics related to the music field and the music industry",
            "tag": "B",
            "is_korean": False,
        },
        {
            "topic": "Talk about research topics and theories in anthropology and cultural sociology",
            "tag": "B",
            "is_korean": False,
        },
        {"topic": "Talking about favorite books", "tag": "C", "is_korean": False},
        {"topic": "Discussing favorite book genres", "tag": "C", "is_korean": False},
        {"topic": "Talking about favorite authors", "tag": "C", "is_korean": False},
        {"topic": "Discussing recent movies watched", "tag": "C", "is_korean": False},
        {"topic": "Talking about favorite TV programs", "tag": "C", "is_korean": False},
        {
            "topic": "Discussing interesting Netflix content",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "Talking about Marvel movies", "tag": "C", "is_korean": False},
        {"topic": "Discussing favorite movie genres", "tag": "C", "is_korean": False},
        {
            "topic": "Talking about life-changing movies or dramas",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "Discussing worst movies or dramas", "tag": "C", "is_korean": False},
        {"topic": "Talking about favorite actors", "tag": "C", "is_korean": False},
        {
            "topic": "Talking about favorite movie directors",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "Discussing K-POP", "tag": "C", "is_korean": False},
        {
            "topic": "Talking about favorite music genres",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "Talking about favorite singers", "tag": "C", "is_korean": False},
        {"topic": "Talking about favorite songs", "tag": "C", "is_korean": False},
        {
            "topic": "Discussing most memorable travel destinations",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Discussing worst travel destinations",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Talking about amusing travel experiences",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Talking about foods eaten during travels",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Talking about MBTI personality types",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "Talking about favorite sports", "tag": "C", "is_korean": False},
        {
            "topic": "Talking about favorite sports stars",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "Discussing activities on holidays", "tag": "C", "is_korean": False},
        {"topic": "Discussing personal hobbies", "tag": "C", "is_korean": False},
        {
            "topic": "Talking about favorite foods or restaurants",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Discussing preferred coffee at cafes",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Talking about favorite musicals or plays",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "Talking about the most liked food", "tag": "C", "is_korean": False},
        {"topic": "Talking about foods one cannot eat", "tag": "C", "is_korean": False},
        {"topic": "Discussing Korean food culture", "tag": "C", "is_korean": False},
        {
            "topic": "Talking about personal alcohol tolerance",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "Talking about favorite drinks", "tag": "C", "is_korean": False},
        {
            "topic": "Discussing desired travel destinations",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "Discussing upcoming travel plans", "tag": "C", "is_korean": False},
        {
            "topic": "Talking about the first overseas trip",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "Discussing travel preparation tips", "tag": "C", "is_korean": False},
        {
            "topic": "Talking about episodes of cultural differences during travel",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "Talking about food allergies", "tag": "C", "is_korean": False},
        {"topic": "Talking about favorite desserts", "tag": "C", "is_korean": False},
        {
            "topic": "Talking about personal characteristics",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "Talking about personal strengths", "tag": "C", "is_korean": False},
        {"topic": "Talking about personal weaknesses", "tag": "C", "is_korean": False},
        {"topic": "Talking about good habits", "tag": "C", "is_korean": False},
        {"topic": "Talking about bad habits", "tag": "C", "is_korean": False},
        {"topic": "Talking about personal interests", "tag": "C", "is_korean": False},
        {"topic": "Talking about personal skills", "tag": "C", "is_korean": False},
        {
            "topic": "Talking about the person one wants to become",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Discussing recent exhibition visits",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Talking about favorite clothing styles",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Discussing preference for dogs or cats",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Discussing happy experiences related to pets",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Talking about experiences of raising pets",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "Talking about Korean street food", "tag": "C", "is_korean": False},
        {
            "topic": "Discussing recommended street food in one's own country",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Talking about Korean delivery culture",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Talking about favorite delivery foods",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "Discussing recent weather", "tag": "C", "is_korean": False},
        {"topic": "Talking about favorite seasons", "tag": "C", "is_korean": False},
        {
            "topic": "Discussing useful apps used recently",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "Talking about one's major", "tag": "C", "is_korean": False},
        {
            "topic": "Discussing reasons for choosing one's major",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Talking about experiences of cooking",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Talking about dishes one is good at cooking",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "Talking about memorable gifts", "tag": "C", "is_korean": False},
        {"topic": "Talking about the favorite month", "tag": "C", "is_korean": False},
        {
            "topic": "Talking about activities on the last Christmas",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Talking about recent favorite YouTubers",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Talking about the happiest moment of the past week",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Talking about memorable high school experiences",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "Talking about one's hometown", "tag": "C", "is_korean": False},
        {
            "topic": "Talking about fulfilling activities",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Describing first impressions with food",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Discussing team projects vs. individual assignments",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "Discussing personal boundaries", "tag": "C", "is_korean": False},
        {
            "topic": "Talking about the most different aspect between how others see you and how you see yourself",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Talking about one's favorite weather",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Discussing actions taken when feeling lonely",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Summer clothes in winter vs. Winter clothes in summer",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "True friendship vs. True love", "tag": "C", "is_korean": False},
        {
            "topic": "Cola without carbonation vs. Pizza without cheese",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Monthly salary of 5 million KRW employee vs. Unemployed with a monthly salary of 2 million KRW",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Talking about actions others should not do",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Discussing the superpower one would want if given a choice",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Instagram banned for a month vs. YouTube banned for a month",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Talking about oneself 10 years from now",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Talking about part-time jobs one would like to try",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Discussing personal part-time job experiences",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Discussing the most enjoyable experience during university life",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Discussing the most challenging experience during university life",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "Talking about favorite colors", "tag": "C", "is_korean": False},
        {
            "topic": "If you could go back 5 years, what would you do?",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "Talking about one's zodiac sign", "tag": "C", "is_korean": False},
        {"topic": "Talking about personal jinxes", "tag": "C", "is_korean": False},
        {
            "topic": "If you could be born as a different animal, what would it be?",
            "tag": "C",
            "is_korean": False,
        },
        {
            "topic": "Meeting someone you like vs. Meeting someone who likes you",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "Talking about drinking habits", "tag": "C", "is_korean": False},
        {
            "topic": "Discussing experiences of seeing ghosts",
            "tag": "C",
            "is_korean": False,
        },
        {"topic": "Talking about personal routines", "tag": "C", "is_korean": False},
        {
            "topic": "Talking about recent shopping experiences",
            "tag": "C",
            "is_korean": False,
        },
    ]
    meta = sa.MetaData()
    meta.reflect(only=('topic',), bind=op.get_bind())
    topic_tbl = sa.Table('topic', meta)
    op.bulk_insert(topic_tbl, topic_data)
